name: hafiz_ijaz_ul_hassan
description: Hello there, I'm Hafiz Ijaz Ul Hassan. This is my personal website, which contains public information that anyone can find on the internet.

publish_to: 'none'

version: 1.1.2+0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.2
  video_player: ^2.10.1


flutter_native_splash:
  image: assets/images/splash.png
  color: "#121212"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/docs/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
          weight: 700